In [5]:
import sys;sys.path.append("..")
from trader.data.binance import Binance
from trader.data.univ import Universe
import pandas as pd
import numpy as np
from binance.enums import ORDER_TYPE_MARKET, SIDE_BUY, SIDE_SELL

In [12]:
univ = Universe()
yay = univ.coins.index.to_list()
yay = [x.upper() + "USDT" for x in yay]
yay

['BTCUSDT',
 'LTCUSDT',
 'BCHUSDT',
 'XLMUSDT',
 'XRPUSDT',
 'ETHUSDT',
 'SOLUSDT',
 'ALGOUSDT',
 'AVAXUSDT',
 'ADAUSDT',
 'MATICUSDT',
 'LINKUSDT',
 'UNIUSDT',
 'SUSHIUSDT',
 'AAVEUSDT',
 'COMPUSDT',
 'YFIUSDT',
 'FILUSDT',
 'MANAUSDT',
 'AXSUSDT',
 'DOGEUSDT',
 'SHIBUSDT']

In [13]:
b = Binance(test=False)

In [14]:
start = pd.to_datetime("2021-01-01")
end = pd.to_datetime("today").floor("D")

In [15]:
bars = b.get_bars(yay, start, end, interval="1h")

In [3]:
acc = b.get_account()

In [4]:
acc

asset
BNB     0.001541
USDT    0.047848
GBP     0.598720
LUNA    2.333528
LUNC    7.517200
Name: free, dtype: float64

In [9]:
acc.set_index("asset").free.astype(np.float64)

asset
BTC      0.000000
LTC      0.000000
ETH      0.000000
NEO      0.000000
BNB      0.001541
           ...
LDO      0.000000
USTC     0.000000
LUNC     7.517200
OP       0.000000
LEVER    0.000000
Name: free, Length: 515, dtype: float64

In [7]:
acc[acc.free >0]

TypeError: '>' not supported between instances of 'str' and 'int'

In [11]:
pd.DataFrame(d["balances"])

  asset             free      locked
0   BNB    1000.00000000  0.00000000
1   BTC       0.99500000  0.00000000
2  BUSD   10000.00000000  0.00000000
3   ETH     100.00000000  0.00000000
4   LTC     500.00000000  0.00000000
5   TRX  500000.00000000  0.00000000
6  USDT   10113.56745000  0.00000000
7   XRP   50000.00000000  0.00000000

In [13]:
get_account(b)

  asset             free      locked
0   BNB    1000.00000000  0.00000000
1   BTC       0.99500000  0.00000000
2  BUSD   10000.00000000  0.00000000
3   ETH     100.00000000  0.00000000
4   LTC     500.00000000  0.00000000
5   TRX  500000.00000000  0.00000000
6  USDT   10113.56745000  0.00000000
7   XRP   50000.00000000  0.00000000

In [ ]:
b.get_bars

In [6]:
create_market_order(b, "BTCUSDT", "s", 0.005, test=False)a

{'symbol': 'BTCUSDT',
 'orderId': 6892963,
 'orderListId': -1,
 'clientOrderId': '0Hg4cgDGI8rgZP7QNMozw3',
 'transactTime': 1658688137113,
 'price': '0.00000000',
 'origQty': '0.00500000',
 'executedQty': '0.00500000',
 'cummulativeQuoteQty': '113.56745000',
 'status': 'FILLED',
 'timeInForce': 'GTC',
 'type': 'MARKET',
 'side': 'SELL',
 'fills': [{'price': '22713.49000000',
   'qty': '0.00500000',
   'commission': '0.00000000',
   'commissionAsset': 'USDT',
   'tradeId': 2924830}]}

In [7]:
b.client.get_account()

{'makerCommission': 0,
 'takerCommission': 0,
 'buyerCommission': 0,
 'sellerCommission': 0,
 'canTrade': True,
 'canWithdraw': False,
 'canDeposit': False,
 'updateTime': 1658688137113,
 'accountType': 'SPOT',
 'balances': [{'asset': 'BNB',
   'free': '1000.00000000',
   'locked': '0.00000000'},
  {'asset': 'BTC', 'free': '0.99500000', 'locked': '0.00000000'},
  {'asset': 'BUSD', 'free': '10000.00000000', 'locked': '0.00000000'},
  {'asset': 'ETH', 'free': '100.00000000', 'locked': '0.00000000'},
  {'asset': 'LTC', 'free': '500.00000000', 'locked': '0.00000000'},
  {'asset': 'TRX', 'free': '500000.00000000', 'locked': '0.00000000'},
  {'asset': 'USDT', 'free': '10113.56745000', 'locked': '0.00000000'},
  {'asset': 'XRP', 'free': '50000.00000000', 'locked': '0.00000000'}],
 'permissions': ['SPOT']}

In [3]:
start = pd.to_datetime("2022-06-01")
end = pd.to_datetime("today").floor("D")
symbol = "BTCUSDT"
interval = "1h"
#klines = b.client.get_historical_klines(symbol=symbol, interval=interval,limit=1000, start_str = str(int(start.timestamp())), end_str=str(int(end.timestamp())))

In [4]:
spot = b.get_bars("BTCUSDT", start, end, "1h", "SPOT")
fut = b.get_bars("BTCUSDT", start, end, "1h", "FUTURE")

In [6]:
spot

,OpenTime,Open,High,Low,Close,Volume,CloseTime,QuoteVolume,NumTrades,TakerBaseVolume,TakerQuoteVolue,Symbol
0,2022-06-01 01:00:00,31936.53,31947.26,31836.99,31926.12,1280.94083,2022-06-01 02:00:00,4.084851e+07,28855,593.95656,1.894059e+07,BTCUSDT
1,2022-06-01 02:00:00,31926.13,31926.13,31731.01,31806.72,1647.05696,2022-06-01 03:00:00,5.239043e+07,32973,713.50400,2.269563e+07,BTCUSDT
2,2022-06-01 03:00:00,31806.71,31806.72,31614.01,31627.30,1937.06614,2022-06-01 04:00:00,6.139687e+07,36931,826.14448,2.618057e+07,BTCUSDT
3,2022-06-01 04:00:00,31627.29,31670.00,31371.45,31566.60,2528.78791,2022-06-01 05:00:00,7.972319e+07,44628,1179.01419,3.717423e+07,BTCUSDT
4,2022-06-01 05:00:00,31566.60,31626.93,31445.76,31622.28,1293.69241,2022-06-01 06:00:00,4.081444e+07,29705,627.55543,1.980049e+07,BTCUSDT
...,...,...,...,...,...,...,...,...,...,...,...,...
692,2022-06-29 21:00:00,20224.04,20357.06,20196.80,20295.35,1443.38271,2022-06-29 22:00:00,2.928279e+07,30903,667.21719,1.353479e+07,BTCUSDT
693,2022-06-29 22:00:00,20295.35,20326.12,20151.77,20213.64,5882.17945,2022-06-29 23:00:00,1.189329e+08,94026,2555.37667,5.166551e+07,BTCUSDT
694,2022-06-29 23:00:00,20213.64,20218.89,20052.74,20123.01,2047.52726,2022-06-30 00:00:00,4.118746e+07,33123,1044.22464,2.100235e+07,BTCUSDT
695,2022-06-30 00:00:00,20123.00,20179.08,20011.17,20037.92,2386.15679,2022-06-30 01:00:00,4.793134e+07,40221,1169.66845,2.349560e+07,BTCUSDT
696,2022-06-30 01:00:00,20037.91,20084.99,19951.08,20018.44,2705.05313,2022-06-30 02:00:00,5.416226e+07,41232,1347.20359,2.697679e+07,BTCUSDT